name: Build
on: [workflow_dispatch]
permissions:
    statuses: write
    contents: read

jobs:
    build-linux-x11-clang:
        name: X11 (Linux, Clang)
        runs-on: ubuntu-latest
        env:
            CC: clang
            CFLAGS: -Werror
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

            - name: Configure shared library
              run: cmake -S . -B build-shared -D BUILD_SHARED_LIBS=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Check result files
              run: ls -al ./build-shared/src

    build-linux-full-clang:
        name: X11+Wayland (Linux, Clang)
        runs-on: ubuntu-latest
        env:
            CC: clang
            CFLAGS: -Werror
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev

            - name: Configure shared library
              run: cmake -S . -B build-shared -D GLFW_BUILD_WAYLAND=ON -D BUILD_SHARED_LIBS=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Check result files
              run: ls -al ./build-shared/src
            - name: Move lib to lwjgl path
              run: |
                  mkdir -p ./native/linux/x64/org/lwjgl3/glfw/
                  cp ./build-shared/src/libglfw.so.3.4 ./native/linux/x64/org/lwjgl3/glfw/libglfw.so
            - uses: actions/upload-artifact@v3
              with:
                path: |
                  ./native
              name: Upload artifact
    build-macos-cocoa-clang:
        name: Cocoa (macOS, Clang)
        runs-on: macos-latest
        env:
            CFLAGS: -Werror
            MACOSX_DEPLOYMENT_TARGET: 10.8
        steps:
            - uses: actions/checkout@v3

            - name: Configure shared library
              run: cmake -S . -B build-shared -D BUILD_SHARED_LIBS=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Check result files
              run: ls -al ./build-shared/src
            - name: Move lib to lwjgl path
              run: |
                  mkdir -p ./native/macos/x64/org/lwjgl3/glfw/
                  cp ./build-shared/src/libglfw.3.4.dylib ./native/macos/x64/org/lwjgl3/glfw/libglfw.dylib
            - uses: actions/upload-artifact@v3
              with:
                path: |
                  ./native
              name: Upload artifact

    build-windows-cross:
        name: Cross-compile for Windows
        runs-on: ubuntu-latest
        env:
            CC: clang
            CFLAGS: -Werror
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev mingw-w64

            - name: Configure shared library
              run: cmake -S . -B build-shared -D GLFW_BUILD_WAYLAND=ON -D BUILD_SHARED_LIBS=ON CMAKE_TOOLCHAIN_FILE=CMake/x86_64-w64-mingw32.cmake
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Check result files
              run: |
                ls -al ./build-shared/src
                ls -al ./build-shared/src/Debug
